import { Golos_Text, Onest } from "next/font/google";
import "@/styles/globals.css";

const golosText = Golos_Text({ subsets: ["cyrillic-ext"], weights: [400, 500, 600, 700] });
const onest = Onest({ subsets: ["latin"], weights: [400, 500, 600, 700] });

export const metadata = {
  title: "MagicAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${golosText.className} ${onest.className}`}>{children}</body>
    </html>
  );
}
